# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 819aac49aa081bfecf1581a55d197df76c9cd9040e3533d676a3aff11d7fad6421b0e4206a2e4c6a1497367c96717b47255e8d13d86798cff9b2d9708ea0fdba

test:
  secret_key_base: daae5f74170ba3aac66b8addb46666bd2e9cdea029f092159d4b9110944500440c057b5d9963877c13c9bb3c0cc5c284ded0a00cdf75fe2885359fe5f56e1825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
